language: generic

sudo: required

addons:
    apt:
        packages:
            - nodejs

after_success: |
    which node &&
    node --version && 
    npm install --global awesome-lint && 
    awesome-lint
